/**
 * LevelIconStatic — Loads pre-generated SVG files for level icons
 *
 * Uses the SVGs generated by scripts/generate-level-icons.ts
 * stored at public/icons/levels/level-NNN.svg
 *
 * Lighter alternative to the programmatic LevelIcon component.
 */

import type { Icon101Variant } from './level-icon';

interface LevelIconStaticProps {
  level: number;
  size?: number;
  className?: string;
  variant101?: Icon101Variant;
}

function getSvgPath(level: number, variant101: Icon101Variant = 'prismatic-crown'): string {
  const clamped = Math.max(1, Math.min(level, 101));
  if (clamped === 101 && variant101 !== 'prismatic-crown') {
    return `/icons/levels/level-101-${variant101}.svg`;
  }
  return `/icons/levels/level-${String(clamped).padStart(3, '0')}.svg`;
}

export function LevelIconStatic({ level, size = 48, className, variant101 }: LevelIconStaticProps) {
  const src = getSvgPath(level, variant101);

  return (
    /* biome-ignore lint/performance/noImgElement: static SVG loaded from public dir */
    <img
      src={src}
      alt={`Level ${level} icon`}
      width={size}
      height={size}
      className={className}
      loading="lazy"
    />
  );
}
