/**
 * Template Engine - Problem Generation System
 *
 * Provides infrastructure for creating mathematical problems from templates:
 * - Template parsing and variable substitution
 * - Deterministic seed-based parameterization (same seed → same problem)
 * - Difficulty scaling
 * - Solution generation with CAS-computed exact graded answers
 * - Hint system
 * - Common mistake detection
 */

import { Complex, solve } from '../../solver';
import { createSeededRandom } from './seeded-rng';

/**
 * Possible parameter values generated by the template engine
 */
export type ParameterValue = number | string | { numerator: number; denominator: number };

/**
 * Template params record - maps parameter names to their generated values.
 * Template callbacks that need typed access should use the `narrow` helper.
 */
export type TemplateParams = Record<string, ParameterValue>;

/**
 * Narrows template params to a typed object with known properties.
 * Bypasses `noUncheckedIndexedAccess` by returning an object with definite keys
 * instead of an index-signature type.
 *
 * Usage in solution/hint/mistake callbacks:
 *   `const { a, b } = narrow<{ a: number; b: number }>(params);`
 *   `const { op } = narrow<{ op: string }>(params);`
 */
export function narrow<T extends Record<string, ParameterValue>>(params: TemplateParams): T {
  return params as unknown as T;
}

/**
 * Parameter specification for template variables
 */
export interface ParameterSpec {
  /** Parameter name */
  name: string;
  /** Type of parameter */
  type: 'integer' | 'real' | 'rational' | 'expression' | 'choice';
  /** Minimum value (for numeric types) */
  min?: number;
  /** Maximum value (for numeric types) */
  max?: number;
  /** Possible choices (for choice type) */
  choices?: ParameterValue[];
  /** Additional constraints (called with the generated numeric value and already-resolved params) */
  constraint?: (value: number, params: Record<string, number>) => boolean;
  /** Description */
  description?: string;
}

/**
 * Canonical answer specification, declared per template and computed
 * from the generated parameters. The engine turns this into a
 * {@link GradedAnswer} at generate() time.
 */
export type CanonicalSpec =
  | { kind: 'solutions'; equation: string; variable: string }
  | { kind: 'expression'; expression: string; variable?: string }
  | { kind: 'number'; value: number; tolerance?: number }
  | { kind: 'assignments'; variables: ReadonlyArray<string>; values: ReadonlyArray<number> };

/**
 * Machine-gradable answer attached to a generated problem instance.
 *
 * - `solutions` — the exact real roots of `equation` (computed via the
 *   closed-form solver), order-insensitive multiset for grading.
 * - `expression` — a canonical expression; student input is graded via
 *   CAS equivalence checking.
 * - `number` — a single numeric value (optionally with a custom
 *   tolerance for π-style answers).
 * - `assignments` — labeled variable values (e.g. systems: x = 2, y = 3).
 */
export type GradedAnswer =
  | {
      kind: 'solutions';
      equation: string;
      variable: string;
      values: ReadonlyArray<number>;
    }
  | { kind: 'expression'; expression: string; variable?: string }
  | { kind: 'number'; value: number; tolerance?: number }
  | { kind: 'assignments'; variables: ReadonlyArray<string>; values: ReadonlyArray<number> };

/**
 * Generated problem instance
 */
export interface ProblemInstance {
  /** Problem statement with substituted values */
  statement: string;
  /** Solution with steps */
  solution: Solution;
  /** Hints for solving */
  hints: string[];
  /** Parameter values used */
  parameters: TemplateParams;
  /** Difficulty level */
  difficulty: 1 | 2 | 3 | 4 | 5;
  /** Common mistakes to avoid */
  commonMistakes: Mistake[];
  /** Seed used to generate this instance (round-trips through URLs) */
  seed: string;
  /** Machine-gradable canonical answer (when the template declares one) */
  graded?: GradedAnswer;
}

/**
 * Solution structure
 */
export interface Solution {
  /** Final answer */
  answer: string;
  /** Step-by-step derivation */
  steps: SolutionStep[];
  /** Answer in different formats */
  alternatives?: string[];
}

/**
 * Single solution step
 */
export interface SolutionStep {
  /** Step description */
  description: string;
  /** Mathematical expression */
  expression: string;
  /** Explanation */
  explanation?: string;
}

/**
 * Common mistake pattern
 */
export interface Mistake {
  /** Incorrect answer pattern */
  incorrectAnswer: string | RegExp;
  /** Explanation of the mistake */
  explanation: string;
  /** Hint to correct it */
  correction: string;
}

/**
 * Solution generator function
 */
export type SolutionGenerator = (params: TemplateParams) => Solution;

/**
 * Hint generator function
 */
export type HintGenerator = (params: TemplateParams, progress?: number) => string;

/**
 * Mistake detector function
 */
export type MistakeDetector = (params: TemplateParams, userAnswer: string) => Mistake | null;

/**
 * Problem template definition
 */
export interface ProblemTemplate {
  /** Unique template ID */
  id: string;
  /** Category (algebra, calculus, etc.) */
  category: string;
  /** Subcategory */
  subcategory?: string;
  /** Difficulty level */
  difficulty: 1 | 2 | 3 | 4 | 5;
  /** Template string with {{variable}} placeholders */
  template: string;
  /** Parameter specifications */
  parameters: ParameterSpec[];
  /** Solution generator */
  solution: SolutionGenerator;
  /** Hint generators (progressive) */
  hints: HintGenerator[];
  /** Common mistake detectors */
  commonMistakes: MistakeDetector[];
  /** Tags for searching */
  tags?: string[];
  /** Prerequisites */
  prerequisites?: string[];
  /** Learning objectives */
  learningObjectives?: string[];
  /**
   * Canonical machine-gradable answer for the generated parameters.
   * When present, generate() computes {@link ProblemInstance.graded}.
   */
  canonical?: (params: TemplateParams) => CanonicalSpec;
}

/**
 * Template Engine for problem generation
 */
export class TemplateEngine {
  private templates = new Map<string, ProblemTemplate>();

  /**
   * Register a template
   */
  register(template: ProblemTemplate): void {
    this.templates.set(template.id, template);
  }

  /**
   * Register multiple templates
   */
  registerMany(templates: ProblemTemplate[]): void {
    templates.forEach((t) => {
      this.register(t);
    });
  }

  /**
   * Generate a problem from a template.
   *
   * Generation is pure and deterministic: the seed creates a local RNG
   * stream, so the same (templateId, seed) pair always produces the
   * identical problem — safe under concurrent generation and React
   * StrictMode double-invocation.
   */
  generate(templateId: string, seed: string | number): ProblemInstance {
    const template = this.templates.get(templateId);
    if (!template) {
      throw new Error(`Template ${templateId} not found`);
    }

    const seedString = String(seed);
    const rng = createSeededRandom(seedString);

    // Generate parameter values
    const parameters = this.generateParameters(template.parameters, rng);

    // Substitute template
    const statement = this.substituteTemplate(template.template, parameters);

    // Generate solution
    const solution = template.solution(parameters);

    // Generate hints
    const hints = template.hints.map((hintGen) => hintGen(parameters));

    // Generate mistake detectors
    const commonMistakes = template.commonMistakes
      .map((detector) => detector(parameters, ''))
      .filter((m): m is Mistake => m !== null);

    // Compute the machine-gradable answer from the canonical spec
    const graded = template.canonical
      ? this.computeGraded(template.canonical(parameters))
      : undefined;

    return {
      statement,
      solution,
      hints,
      parameters,
      difficulty: template.difficulty,
      commonMistakes,
      seed: seedString,
      ...(graded ? { graded } : {}),
    };
  }

  /**
   * Generate multiple problems from a template.
   * Seeds are derived as `${baseSeed}:${i}`, so batches are reproducible.
   */
  generateBatch(templateId: string, count: number, baseSeed?: string): ProblemInstance[] {
    const problems: ProblemInstance[] = [];
    const base = baseSeed ?? templateId;

    for (let i = 0; i < count; i++) {
      problems.push(this.generate(templateId, `${base}:${i}`));
    }

    return problems;
  }

  /**
   * Turn a canonical spec into a graded answer.
   * For `solutions`, roots are computed via the exact closed-form solver;
   * if no real closed-form solution can be supported, no graded answer is
   * attached (grading falls back to the display answer, never guesses).
   */
  private computeGraded(spec: CanonicalSpec): GradedAnswer | undefined {
    switch (spec.kind) {
      case 'solutions': {
        try {
          const solutions = solve(spec.equation, spec.variable);
          const values: number[] = [];
          for (const sol of solutions) {
            if (typeof sol.value === 'number') {
              if (!Number.isFinite(sol.value)) return undefined;
              values.push(sol.value);
            } else if (sol.value instanceof Complex) {
              if (Math.abs(sol.value.imag) > 1e-9) return undefined;
              values.push(sol.value.real);
            }
          }
          if (values.length === 0) return undefined;
          return {
            kind: 'solutions',
            equation: spec.equation,
            variable: spec.variable,
            values,
          };
        } catch {
          return undefined;
        }
      }
      case 'expression':
        return {
          kind: 'expression',
          expression: spec.expression,
          ...(spec.variable !== undefined ? { variable: spec.variable } : {}),
        };
      case 'number':
        if (!Number.isFinite(spec.value)) return undefined;
        return {
          kind: 'number',
          value: spec.value,
          ...(spec.tolerance !== undefined ? { tolerance: spec.tolerance } : {}),
        };
      case 'assignments':
        if (spec.variables.length !== spec.values.length || spec.variables.length === 0) {
          return undefined;
        }
        if (spec.values.some((v) => !Number.isFinite(v))) return undefined;
        return { kind: 'assignments', variables: spec.variables, values: spec.values };
      default:
        return undefined;
    }
  }

  /**
   * Find templates by criteria
   */
  find(criteria: {
    category?: string;
    difficulty?: number | number[];
    tags?: string[];
  }): ProblemTemplate[] {
    let templates = Array.from(this.templates.values());

    if (criteria.category) {
      templates = templates.filter((t) => t.category === criteria.category);
    }

    if (criteria.difficulty !== undefined) {
      const difficulties = Array.isArray(criteria.difficulty)
        ? criteria.difficulty
        : [criteria.difficulty];
      templates = templates.filter((t) => difficulties.includes(t.difficulty));
    }

    if (criteria.tags) {
      templates = templates.filter((t) => criteria.tags?.some((tag) => t.tags?.includes(tag)));
    }

    return templates;
  }

  /**
   * Get template by ID
   */
  getTemplate(id: string): ProblemTemplate | undefined {
    return this.templates.get(id);
  }

  /**
   * Generate parameters for a template
   */
  private generateParameters(specs: ParameterSpec[], rng: () => number): TemplateParams {
    const params: TemplateParams = {};

    for (const spec of specs) {
      let value: ParameterValue;
      let attempts = 0;
      const maxAttempts = 100;

      // Build a numeric-only view of already-resolved params for constraint callbacks
      const numericParams: Record<string, number> = {};
      for (const [k, v] of Object.entries(params)) {
        if (typeof v === 'number') {
          numericParams[k] = v;
        }
      }

      do {
        value = this.generateParameter(spec, rng);
        attempts++;
      } while (
        spec.constraint &&
        !spec.constraint(value as number, numericParams) &&
        attempts < maxAttempts
      );

      if (attempts >= maxAttempts) {
        throw new Error(`Could not generate valid value for parameter ${spec.name}`);
      }

      params[spec.name] = value;
    }

    return params;
  }

  /**
   * Generate a single parameter value
   */
  private generateParameter(spec: ParameterSpec, rng: () => number): ParameterValue {
    switch (spec.type) {
      case 'integer': {
        const min = spec.min ?? 0;
        const max = spec.max ?? 100;
        return Math.floor(rng() * (max - min + 1)) + min;
      }

      case 'real': {
        const min = spec.min ?? 0;
        const max = spec.max ?? 1;
        return rng() * (max - min) + min;
      }

      case 'rational': {
        const numerator = this.generateParameter({ ...spec, type: 'integer' }, rng) as number;
        let denominator: number;
        do {
          denominator = this.generateParameter({ ...spec, type: 'integer', min: 1 }, rng) as number;
        } while (denominator === 0);
        return { numerator, denominator };
      }

      case 'choice': {
        if (!spec.choices || spec.choices.length === 0) {
          throw new Error(`No choices provided for parameter ${spec.name}`);
        }
        const index = Math.floor(rng() * spec.choices.length);
        return spec.choices[index]!;
      }

      case 'expression': {
        // Generate simple expressions
        return this.generateSimpleExpression(rng);
      }

      default:
        throw new Error(`Unknown parameter type: ${spec.type}`);
    }
  }

  /**
   * Substitute template variables
   */
  private substituteTemplate(template: string, parameters: TemplateParams): string {
    let result = template;

    for (const [key, value] of Object.entries(parameters)) {
      const placeholder = new RegExp(`{{${key}}}`, 'g');
      const replacement = this.formatValue(value);
      result = result.replace(placeholder, replacement);
    }

    return result;
  }

  /**
   * Format a value for display
   */
  private formatValue(value: ParameterValue): string {
    if (typeof value === 'number') {
      return value.toString();
    }

    if (typeof value === 'object' && 'numerator' in value && 'denominator' in value) {
      return `\\frac{${value.numerator}}{${value.denominator}}`;
    }

    return String(value);
  }

  /**
   * Generate a simple algebraic expression
   */
  private generateSimpleExpression(rng: () => number): string {
    const operators = ['+', '-', '*'];
    const operator = operators[Math.floor(rng() * operators.length)];
    const a = Math.floor(rng() * 10) + 1;
    const b = Math.floor(rng() * 10) + 1;

    return `${a} ${operator} ${b}`;
  }

  /**
   * Get all registered templates
   */
  getAll(): ProblemTemplate[] {
    return Array.from(this.templates.values());
  }

  /**
   * Get statistics
   */
  getStats(): {
    totalTemplates: number;
    byCategory: Map<string, number>;
    byDifficulty: Map<number, number>;
  } {
    const templates = this.getAll();
    const byCategory = new Map<string, number>();
    const byDifficulty = new Map<number, number>();

    for (const template of templates) {
      byCategory.set(template.category, (byCategory.get(template.category) || 0) + 1);
      byDifficulty.set(template.difficulty, (byDifficulty.get(template.difficulty) || 0) + 1);
    }

    return {
      totalTemplates: templates.length,
      byCategory,
      byDifficulty,
    };
  }
}

/**
 * Global template engine instance
 */
export const templateEngine = new TemplateEngine();

/**
 * Helper to create a template
 */
export function createTemplate(template: ProblemTemplate): ProblemTemplate {
  return template;
}
