/**
 * Template Engine - Problem Generation System
 *
 * Provides infrastructure for creating mathematical problems from templates:
 * - Template parsing and variable substitution
 * - Difficulty scaling
 * - Solution generation
 * - Hint system
 * - Common mistake detection
 */

/**
 * Possible parameter values generated by the template engine
 */
export type ParameterValue = number | string | { numerator: number; denominator: number };

/**
 * Template params record - maps parameter names to their generated values.
 * Template callbacks that need typed access should use the `narrow` helper.
 */
export type TemplateParams = Record<string, ParameterValue>;

/**
 * Narrows template params to a typed object with known properties.
 * Bypasses `noUncheckedIndexedAccess` by returning an object with definite keys
 * instead of an index-signature type.
 *
 * Usage in solution/hint/mistake callbacks:
 *   `const { a, b } = narrow<{ a: number; b: number }>(params);`
 *   `const { op } = narrow<{ op: string }>(params);`
 */
export function narrow<T extends Record<string, ParameterValue>>(params: TemplateParams): T {
  return params as unknown as T;
}

/**
 * Parameter specification for template variables
 */
export interface ParameterSpec {
  /** Parameter name */
  name: string;
  /** Type of parameter */
  type: 'integer' | 'real' | 'rational' | 'expression' | 'choice';
  /** Minimum value (for numeric types) */
  min?: number;
  /** Maximum value (for numeric types) */
  max?: number;
  /** Possible choices (for choice type) */
  choices?: ParameterValue[];
  /** Additional constraints (called with the generated numeric value and already-resolved params) */
  constraint?: (value: number, params: Record<string, number>) => boolean;
  /** Description */
  description?: string;
}

/**
 * Generated problem instance
 */
export interface ProblemInstance {
  /** Problem statement with substituted values */
  statement: string;
  /** Solution with steps */
  solution: Solution;
  /** Hints for solving */
  hints: string[];
  /** Parameter values used */
  parameters: TemplateParams;
  /** Difficulty level */
  difficulty: 1 | 2 | 3 | 4 | 5;
  /** Common mistakes to avoid */
  commonMistakes: Mistake[];
}

/**
 * Solution structure
 */
export interface Solution {
  /** Final answer */
  answer: string;
  /** Step-by-step derivation */
  steps: SolutionStep[];
  /** Answer in different formats */
  alternatives?: string[];
}

/**
 * Single solution step
 */
export interface SolutionStep {
  /** Step description */
  description: string;
  /** Mathematical expression */
  expression: string;
  /** Explanation */
  explanation?: string;
}

/**
 * Common mistake pattern
 */
export interface Mistake {
  /** Incorrect answer pattern */
  incorrectAnswer: string | RegExp;
  /** Explanation of the mistake */
  explanation: string;
  /** Hint to correct it */
  correction: string;
}

/**
 * Solution generator function
 */
export type SolutionGenerator = (params: TemplateParams) => Solution;

/**
 * Hint generator function
 */
export type HintGenerator = (params: TemplateParams, progress?: number) => string;

/**
 * Mistake detector function
 */
export type MistakeDetector = (params: TemplateParams, userAnswer: string) => Mistake | null;

/**
 * Problem template definition
 */
export interface ProblemTemplate {
  /** Unique template ID */
  id: string;
  /** Category (algebra, calculus, etc.) */
  category: string;
  /** Subcategory */
  subcategory?: string;
  /** Difficulty level */
  difficulty: 1 | 2 | 3 | 4 | 5;
  /** Template string with {{variable}} placeholders */
  template: string;
  /** Parameter specifications */
  parameters: ParameterSpec[];
  /** Solution generator */
  solution: SolutionGenerator;
  /** Hint generators (progressive) */
  hints: HintGenerator[];
  /** Common mistake detectors */
  commonMistakes: MistakeDetector[];
  /** Tags for searching */
  tags?: string[];
  /** Prerequisites */
  prerequisites?: string[];
  /** Learning objectives */
  learningObjectives?: string[];
}

/**
 * Template Engine for problem generation
 */
export class TemplateEngine {
  private templates = new Map<string, ProblemTemplate>();
  private random = Math.random;

  /**
   * Register a template
   */
  register(template: ProblemTemplate): void {
    this.templates.set(template.id, template);
  }

  /**
   * Register multiple templates
   */
  registerMany(templates: ProblemTemplate[]): void {
    templates.forEach((t) => this.register(t));
  }

  /**
   * Generate a problem from a template
   */
  generate(templateId: string, seed?: number): ProblemInstance {
    const template = this.templates.get(templateId);
    if (!template) {
      throw new Error(`Template ${templateId} not found`);
    }

    // Use seed for reproducibility
    if (seed !== undefined) {
      this.random = this.seededRandom(seed);
    }

    // Generate parameter values
    const parameters = this.generateParameters(template.parameters);

    // Substitute template
    const statement = this.substituteTemplate(template.template, parameters);

    // Generate solution
    const solution = template.solution(parameters);

    // Generate hints
    const hints = template.hints.map((hintGen) => hintGen(parameters));

    // Generate mistake detectors
    const commonMistakes = template.commonMistakes
      .map((detector) => detector(parameters, ''))
      .filter((m): m is Mistake => m !== null);

    return {
      statement,
      solution,
      hints,
      parameters,
      difficulty: template.difficulty,
      commonMistakes,
    };
  }

  /**
   * Generate multiple problems from a template
   */
  generateBatch(templateId: string, count: number): ProblemInstance[] {
    const problems: ProblemInstance[] = [];

    for (let i = 0; i < count; i++) {
      problems.push(this.generate(templateId, i));
    }

    return problems;
  }

  /**
   * Find templates by criteria
   */
  find(criteria: {
    category?: string;
    difficulty?: number | number[];
    tags?: string[];
  }): ProblemTemplate[] {
    let templates = Array.from(this.templates.values());

    if (criteria.category) {
      templates = templates.filter((t) => t.category === criteria.category);
    }

    if (criteria.difficulty !== undefined) {
      const difficulties = Array.isArray(criteria.difficulty)
        ? criteria.difficulty
        : [criteria.difficulty];
      templates = templates.filter((t) => difficulties.includes(t.difficulty));
    }

    if (criteria.tags) {
      templates = templates.filter((t) => criteria.tags?.some((tag) => t.tags?.includes(tag)));
    }

    return templates;
  }

  /**
   * Get template by ID
   */
  getTemplate(id: string): ProblemTemplate | undefined {
    return this.templates.get(id);
  }

  /**
   * Generate parameters for a template
   */
  private generateParameters(specs: ParameterSpec[]): TemplateParams {
    const params: TemplateParams = {};

    for (const spec of specs) {
      let value: ParameterValue;
      let attempts = 0;
      const maxAttempts = 100;

      // Build a numeric-only view of already-resolved params for constraint callbacks
      const numericParams: Record<string, number> = {};
      for (const [k, v] of Object.entries(params)) {
        if (typeof v === 'number') {
          numericParams[k] = v;
        }
      }

      do {
        value = this.generateParameter(spec);
        attempts++;
      } while (
        spec.constraint &&
        !spec.constraint(value as number, numericParams) &&
        attempts < maxAttempts
      );

      if (attempts >= maxAttempts) {
        throw new Error(`Could not generate valid value for parameter ${spec.name}`);
      }

      params[spec.name] = value;
    }

    return params;
  }

  /**
   * Generate a single parameter value
   */
  private generateParameter(spec: ParameterSpec): ParameterValue {
    switch (spec.type) {
      case 'integer': {
        const min = spec.min ?? 0;
        const max = spec.max ?? 100;
        return Math.floor(this.random() * (max - min + 1)) + min;
      }

      case 'real': {
        const min = spec.min ?? 0;
        const max = spec.max ?? 1;
        return this.random() * (max - min) + min;
      }

      case 'rational': {
        const numerator = this.generateParameter({ ...spec, type: 'integer' }) as number;
        let denominator: number;
        do {
          denominator = this.generateParameter({ ...spec, type: 'integer', min: 1 }) as number;
        } while (denominator === 0);
        return { numerator, denominator };
      }

      case 'choice': {
        if (!spec.choices || spec.choices.length === 0) {
          throw new Error(`No choices provided for parameter ${spec.name}`);
        }
        const index = Math.floor(this.random() * spec.choices.length);
        return spec.choices[index]!;
      }

      case 'expression': {
        // Generate simple expressions
        return this.generateSimpleExpression();
      }

      default:
        throw new Error(`Unknown parameter type: ${spec.type}`);
    }
  }

  /**
   * Substitute template variables
   */
  private substituteTemplate(template: string, parameters: TemplateParams): string {
    let result = template;

    for (const [key, value] of Object.entries(parameters)) {
      const placeholder = new RegExp(`{{${key}}}`, 'g');
      const replacement = this.formatValue(value);
      result = result.replace(placeholder, replacement);
    }

    return result;
  }

  /**
   * Format a value for display
   */
  private formatValue(value: ParameterValue): string {
    if (typeof value === 'number') {
      return value.toString();
    }

    if (typeof value === 'object' && 'numerator' in value && 'denominator' in value) {
      return `\\frac{${value.numerator}}{${value.denominator}}`;
    }

    return String(value);
  }

  /**
   * Generate a simple algebraic expression
   */
  private generateSimpleExpression(): string {
    const operators = ['+', '-', '*'];
    const operator = operators[Math.floor(this.random() * operators.length)];
    const a = Math.floor(this.random() * 10) + 1;
    const b = Math.floor(this.random() * 10) + 1;

    return `${a} ${operator} ${b}`;
  }

  /**
   * Seeded random number generator
   */
  private seededRandom(seed: number): () => number {
    let state = seed;

    return () => {
      state = (state * 1664525 + 1013904223) % 4294967296;
      return state / 4294967296;
    };
  }

  /**
   * Get all registered templates
   */
  getAll(): ProblemTemplate[] {
    return Array.from(this.templates.values());
  }

  /**
   * Get statistics
   */
  getStats(): {
    totalTemplates: number;
    byCategory: Map<string, number>;
    byDifficulty: Map<number, number>;
  } {
    const templates = this.getAll();
    const byCategory = new Map<string, number>();
    const byDifficulty = new Map<number, number>();

    for (const template of templates) {
      byCategory.set(template.category, (byCategory.get(template.category) || 0) + 1);
      byDifficulty.set(template.difficulty, (byDifficulty.get(template.difficulty) || 0) + 1);
    }

    return {
      totalTemplates: templates.length,
      byCategory,
      byDifficulty,
    };
  }
}

/**
 * Global template engine instance
 */
export const templateEngine = new TemplateEngine();

/**
 * Helper to create a template
 */
export function createTemplate(template: ProblemTemplate): ProblemTemplate {
  return template;
}
